### ISSUE TITLE
[BUG] TypeError:  Cannot read properties of null (reading 'sdp')

### ISSUE THREAD

**Issue by wjlroe** [twilio/twilio-voice.js#100]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-node) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**

Not raising exceptions due to calling `sdp` on a `null` value.

**Actual behavior:**

Periodically, we get this exception raised by the voice-sdk:

    TypeError: Cannot read properties of null (reading 'sdp')

Here is the backtrace:

```
webpack://[name]/./node_modules/@twilio/voice-sdk/es5/twilio/rtc/rtcpc.js:120:in sdp
webpack://[name]/./node_modules/@twilio/voice-sdk/es5/twilio/call.js:250:in getSDP
webpack://[name]/./node_modules/events/events.js:158:in ReflectApply
webpack://[name]/./node_modules/@twilio/voice-sdk/es5/twilio/pstream.js:179:in emit
webpack://[name]/./node_modules/events/events.js:153:in ReflectApply
webpack://[name]/./node_modules/@twilio/voice-sdk/es5/twilio/wstransport.js:173:in emit
```

We have seen this error twice in the last month, with a user base of ~400 users.

**Software versions:**

 - Browser(s): Chrome
 - Operating System: ChromeOS
 - twilio.js: 2.1.1
 - Third-party libraries (e.g., Angular, React, etc.): ReactJS 17.0.39

**Comment by djeer** [comment]
I'm not the topic-starter, yet...
We're having huge spike of such errors in the last two days.
- Our customers report call interruptions
- Three "headless chrome" events caused exactly three calls test pipeline failures at 15:06 02 Aug 2022 UTC and 11:51, 11:58 03 Aug 2022 UTC

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/3585469/182622259-ce98e66b-e505-4904-9920-a8e31f735173.png">

**Comment by djeer** [comment]
duplicated report is here https://github.com/twilio/twilio-voice.js/issues/98

**Comment by djeer** [comment]
Here is our stack trace if it might help

<img width="904" alt="image" src="https://user-images.githubusercontent.com/3585469/182630248-c15b5a65-8427-42ba-a154-a5b2ce444ec2.png">

**Comment by charliesantos** [comment]
Hello everyone. Apologies for the delay. We're not able to reproduce this internally, unfortunately.
Do you have client logs and callsid by any chance?

**Comment by iamplo** [comment]
Seeing this as well. We can reproduce under the following conditions:

1. Receive incoming call to client browser (Chrome).
2. Reject the pending call using `call.reject()`.
3. Refresh token using `device.updateToken(newtoken)`.
4. Observe the error thrown
5. The same error is thrown and continues to throw at each updateToken interval.

Only happening after `reject()`

```
Uncaught TypeError: Cannot read properties of null (reading 'getSDP')
    at t.<anonymous> (call.ts:1081:36)
    at t.emit (events.js:158:7)
    at t._handleTransportMessage (pstream.js:179:8)
    at t.emit (events.js:153:5)
    at WebSocket.<anonymous> (wstransport.ts:453:10)
(anonymous) @ call.ts:1081
(anonymous) @ events.js:158
(anonymous) @ pstream.js:179
(anonymous) @ events.js:153
(anonymous) @ wstransport.ts:453

```
SPA React 17.0.1
@twilio/voice-sdk 2.1.2
Browser: Chrome Version 107.0.5304.121 (Official Build) (x86_64)
MacOS: Ventura 13.0.1

**Comment by charliesantos** [comment]
Thanks for the repro steps @iamplo . I submitted an internal ticket to track this issue.

**Comment by gwing33** [comment]
We also run into this, we get about ~1k errors a day due to this, 52k total over the last 4 months.

<img width="1689" alt="image" src="https://user-images.githubusercontent.com/160089/223489082-fcbfc833-48d5-4aec-be25-0883565083a2.png">

**Comment by ppascualv** [comment]
I had the same issue following @iamplo steps with the last version, is there any fix coming?

**Comment by charliesantos** [comment]
Thanks for the ping. It's currently in our roadmap but no accurate date yet.

**Comment by charliesantos** [comment]
Should be fixed in 2.4.0

**Comment by wjlroe** [comment]
This error is still occurring with twilio-voice JS SDK version 2.4.0, same stack trace.

**Comment by charliesantos** [comment]
Thanks @wjlroe . I see you submitted #163 . It might be a different repro steps than what @iamplo mentioned in the [above comments](https://github.com/twilio/twilio-voice.js/issues/100#issuecomment-1360879345). Let's address your issue in #163
