### ISSUE TITLE
[BUG] Twilio error code not being returned when microphone access is blocked

### ISSUE THREAD

**Issue by chsweet** [twilio/twilio-voice.js#95]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-node) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

Block microphone access in browser. Create a new Device

``` js script
  const { Device } = import('@twilio/voice-sdk');
  device = new Twilio.Device(token);

  device.on('error', twilioError => {
    console.log(twilioError);
  });

  device.connect();
```

**Expected behavior:**

When a new `Device` is created and the user has denied access to microphone we should be receiving the Twilio error code 31401 (updated from [31208](https://www.twilio.com/docs/voice/sdks/javascript/migrating-to-js-voice-sdk-20#update-error-codes:~:text=and%20other%20SDKs.-,Update%20error%20codes,-With%20the%20transition)) should be returned.

**Actual behavior:**

We are not receiving the Twilio error code when the user has denied access to microphone. Instead we are getting an error. Slightly different in Chrome, Firefox, and Safari.

**Chrome**
  error  `Uncaught (in promise) TypeError: Cannot ready properties of null (reading 'updatePreferredURI'`

![Screen Shot 2022-06-13 at 12 54 19 PM](https://user-images.githubusercontent.com/81600649/173436957-807ab96f-6d82-497c-bd08-af4625d74f02.png)

**Firefox** 
error `Uncaught (in promise) TypeError: f._stream is null`

<img width="595" alt="Screen Shot 2022-06-13 at 4 37 47 PM" src="https://user-images.githubusercontent.com/81600649/173460061-327c7fd3-7752-463e-aa09-1da2f54b3ada.png">

**Safari** 
error `Unhandled Promise Rejections: TypeError: null is not an object (evaluating 'f._stream.updatePreferredURI`

<img width="677" alt="Screen Shot 2022-06-13 at 4 50 52 PM" src="https://user-images.githubusercontent.com/81600649/173463757-91254d4f-c716-4ff9-b6f7-65c78e6d4007.png">

**Software versions:**

 - [ ] Browser(s): Chrome, Firefox, & Safari
 - [ ] twilio.js: 2.0.1

**Comment by mhuynh5757** [comment]
Hi @chsweet, the team is tracking this internally and we've created a ticket for this. Thanks!

**Comment by ostap0207** [comment]
Are there any updates on ETA? User denying microphone permissions is a fairly common use case, so this blocks us from migrating from the v1 to v2 Twilio client.

**Comment by SiimMardus** [comment]
Found that in `maybeUnsetPreferredUri` function, (which is called also when there is an error from Call and `call` status `closed`), it calls `this._stream.updatePreferredURI(null);`, but in our case the `_stream` is null.

Created a fork and a commit to check if stream exists, before calling `updatePreferredURI` on it. Tested it out with our use case and it worked like it should again.

https://github.com/salemove/twilio-voice.js/pull/1/commits/6fd91d9c3c563f8948a7f8e36cdf2e73356231f9

**Comment by samusgray** [comment]
Great catch! Thanks so much.

**Comment by samusgray** [comment]
Can we prioritize a code review on the PR Siim submitted? 🙏 That looks like it may solve the problem.

**Comment by mhuynh5757** [comment]
Hi @samusgray apologies for the delays. The team will discuss priorities to see when we can investigate this further.

**Comment by charliesantos** [comment]
I left a review on the PR @samusgray

**Comment by samusgray** [comment]
Thank you so much! 🙏 cc @SiimMardus :)

**Comment by charliesantos** [comment]
Should be fixed in https://github.com/twilio/twilio-voice.js/pull/144 and will be released soon.
Closing this now.

**Comment by samusgray** [comment]
Hello again, we upgraded to the latest and are still seeing this issue, just in a slightly different location in the codebase. 

```
Cannot read properties of null (reading 'updatePreferredURI')
/node_modules/@twilio/voice-sdk/es5/twilio/device.js:1014:46 maybeUnsetPreferredUri
/node_modules/@twilio/voice-sdk/es5/twilio/device.js:1039:32 t.<anonymous>
/node_modules/events/events.js:158:6 c.emit
/node_modules/@twilio/voice-sdk/es5/twilio/call.js:859:18 
```

We're certain that when this error gets thrown it results in a broken user experience for our customers, so finally getting it fixed is a really high priority for us. Is there anything we can do to help debug or track down the root cause? Happy to provide any more information that may be useful.

**Comment by charliesantos** [comment]
@samusgray what version did you upgrade to? The fix for this issue hasn't been released yet and still under internal testing.

**Comment by samusgray** [comment]
Oh, I didn't realize. We bumped to the latest and I noticed the error go away in our bug tracker, only to realize it popped back up at a different location, prompting this post. Sorry to bother! 

Any rough idea on when you you're aiming to have the next release out?

**Comment by charliesantos** [comment]
@samusgray no worries! It should come out any day now. If you want to test sooner, please feel free to use the RC version. https://github.com/twilio/twilio-voice.js/releases/tag/2.3.2-rc1

**Comment by samusgray** [comment]
Amazing. I'll start testing the RC in our staging envs. Thanks so much!
